# Kasstroomprojectie rekenvoorbeelden

## Ouderdomspensioen (OP)

We gebruiken gemakshalve de Python package **pandas** (https://pandas.pydata.org/) om een OP voorbeeld door te rekenen. Pandas is handig voor tabulaire gegevens met verschillende datatypes per kolom maar met een gemeenschappelijk index. Voor hoger-dimensionale data is het minder geschikt, en we zullen voor het PP voorbeeld dan ook overstappen naar NumPy.

Allereerste importeren we de pandas package:

In [1]:
import pandas as pd

Vervolgens laden we een zogenaamd *dataframe* in aan met gegevens uit een CSV bestand:

In [2]:
df = pd.read_csv("data.csv", index_col="jaar")
df    

rente  overlevingskans  betaling
jaar                                  
2025   0.05              0.9         0
2026   0.05              0.9         0
2027   0.05              0.9         1
2028   0.05              0.9         1
2029   0.05              0.9         1
2030   0.05              0.9         1
2031   0.05              0.9         1
2032   0.05              0.9         1
2033   0.05              0.9         1
2034   0.05              0.9         1

Scalaire operator op kolommen worden automatisch gevectoriseerd:

In [3]:
df.rente + 1

jaar
2025    1.05
2026    1.05
2027    1.05
2028    1.05
2029    1.05
2030    1.05
2031    1.05
2032    1.05
2033    1.05
2034    1.05
Name: rente, dtype: float64

De cumulatieve rente kunnen  we uitrekenen met de functie [cumprod()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumprod.html). We stoppen de uitkomst weer meteen in het dataframe als een nieuwe kolom:

In [4]:
df["cumulatieve_rente"] = (df.rente + 1).cumprod() - 1
df

rente  overlevingskans  betaling  cumulatieve_rente
jaar                                                     
2025   0.05              0.9         0           0.050000
2026   0.05              0.9         0           0.102500
2027   0.05              0.9         1           0.157625
2028   0.05              0.9         1           0.215506
2029   0.05              0.9         1           0.276282
2030   0.05              0.9         1           0.340096
2031   0.05              0.9         1           0.407100
2032   0.05              0.9         1           0.477455
2033   0.05              0.9         1           0.551328
2034   0.05              0.9         1           0.628895

We doen hetzelfde met de overlevingskansen:

In [5]:
df["cumulatieve_overlevingskans"] = df.overlevingskans.cumprod()
df

rente  overlevingskans  betaling  cumulatieve_rente  \
jaar                                                        
2025   0.05              0.9         0           0.050000   
2026   0.05              0.9         0           0.102500   
2027   0.05              0.9         1           0.157625   
2028   0.05              0.9         1           0.215506   
2029   0.05              0.9         1           0.276282   
2030   0.05              0.9         1           0.340096   
2031   0.05              0.9         1           0.407100   
2032   0.05              0.9         1           0.477455   
2033   0.05              0.9         1           0.551328   
2034   0.05              0.9         1           0.628895   

      cumulatieve_overlevingskans  
jaar                               
2025                     0.900000  
2026                     0.810000  
2027                     0.729000  
2028                     0.656100  
2029                     0.590490  
2030                     0.531441  
2031                     0.478297  
2032                     0.430467  
2033                     0.387420  
2034                     0.348678

De effectieve betaling (of wel de uitkering per euro aanspraak) is dan:

In [6]:
df["effectieve_betaling"] = df.betaling * df.cumulatieve_overlevingskans
df

rente  overlevingskans  betaling  cumulatieve_rente  \
jaar                                                        
2025   0.05              0.9         0           0.050000   
2026   0.05              0.9         0           0.102500   
2027   0.05              0.9         1           0.157625   
2028   0.05              0.9         1           0.215506   
2029   0.05              0.9         1           0.276282   
2030   0.05              0.9         1           0.340096   
2031   0.05              0.9         1           0.407100   
2032   0.05              0.9         1           0.477455   
2033   0.05              0.9         1           0.551328   
2034   0.05              0.9         1           0.628895   

      cumulatieve_overlevingskans  effectieve_betaling  
jaar                                                    
2025                     0.900000             0.000000  
2026                     0.810000             0.000000  
2027                     0.729000             0.729000  
2028                     0.656100             0.656100  
2029                     0.590490             0.590490  
2030                     0.531441             0.531441  
2031                     0.478297             0.478297  
2032                     0.430467             0.430467  
2033                     0.387420             0.387420  
2034                     0.348678             0.348678

Om de factor uit rekenen hebben we de verdisconteerde effectieve betaling nodig:

In [7]:
df["verdisconteerde_effectieve_betaling"] = df.effectieve_betaling / ( 1 + df.cumulatieve_rente)
df

rente  overlevingskans  betaling  cumulatieve_rente  \
jaar                                                        
2025   0.05              0.9         0           0.050000   
2026   0.05              0.9         0           0.102500   
2027   0.05              0.9         1           0.157625   
2028   0.05              0.9         1           0.215506   
2029   0.05              0.9         1           0.276282   
2030   0.05              0.9         1           0.340096   
2031   0.05              0.9         1           0.407100   
2032   0.05              0.9         1           0.477455   
2033   0.05              0.9         1           0.551328   
2034   0.05              0.9         1           0.628895   

      cumulatieve_overlevingskans  effectieve_betaling  \
jaar                                                     
2025                     0.900000             0.000000   
2026                     0.810000             0.000000   
2027                     0.729000             0.729000   
2028                     0.656100             0.656100   
2029                     0.590490             0.590490   
2030                     0.531441             0.531441   
2031                     0.478297             0.478297   
2032                     0.430467             0.430467   
2033                     0.387420             0.387420   
2034                     0.348678             0.348678   

      verdisconteerde_effectieve_betaling  
jaar                                       
2025                             0.000000  
2026                             0.000000  
2027                             0.629738  
2028                             0.539775  
2029                             0.462664  
2030                             0.396569  
2031                             0.339917  
2032                             0.291357  
2033                             0.249735  
2034                             0.214058

De actuarieele factor is de som van de verdisconteerde uitkering:

In [8]:
factor = df.verdisconteerde_effectieve_betaling.sum()
factor

np.float64(3.123813371698276)

De aanspraak wordt dan:

In [9]:
kapitaal = 100_000
aanspraak = kapitaal / factor
aanspraak

np.float64(32012.155689580944)

En de uiteindelijke kasstroom:

In [10]:
df["kasstroom"] = df.effectieve_betaling * aanspraak
df

rente  overlevingskans  betaling  cumulatieve_rente  \
jaar                                                        
2025   0.05              0.9         0           0.050000   
2026   0.05              0.9         0           0.102500   
2027   0.05              0.9         1           0.157625   
2028   0.05              0.9         1           0.215506   
2029   0.05              0.9         1           0.276282   
2030   0.05              0.9         1           0.340096   
2031   0.05              0.9         1           0.407100   
2032   0.05              0.9         1           0.477455   
2033   0.05              0.9         1           0.551328   
2034   0.05              0.9         1           0.628895   

      cumulatieve_overlevingskans  effectieve_betaling  \
jaar                                                     
2025                     0.900000             0.000000   
2026                     0.810000             0.000000   
2027                     0.729000             0.729000   
2028                     0.656100             0.656100   
2029                     0.590490             0.590490   
2030                     0.531441             0.531441   
2031                     0.478297             0.478297   
2032                     0.430467             0.430467   
2033                     0.387420             0.387420   
2034                     0.348678             0.348678   

      verdisconteerde_effectieve_betaling     kasstroom  
jaar                                                     
2025                             0.000000      0.000000  
2026                             0.000000      0.000000  
2027                             0.629738  23336.861498  
2028                             0.539775  21003.175348  
2029                             0.462664  18902.857813  
2030                             0.396569  17012.572032  
2031                             0.339917  15311.314829  
2032                             0.291357  13780.183346  
2033                             0.249735  12402.165011  
2034                             0.214058  11161.948510

Ter controle: de som van de verdisconteerde kasstroom moet gelijk zijn aan het oorspronkelijke kapitaal:

In [11]:
(df.kasstroom / ( 1 + df.cumulatieve_rente)).sum()

np.float64(100000.0)

De som van de onverdisconteerde kasstroom is hetzelfde als wat we zagen in de presentatie:

In [12]:
df.kasstroom.sum()

np.float64(132911.07838631232)

## Ouderdomspensioen met twee staten

We schakelen nu over naar het volledige twee-staten model voor het OP. Hierboven hebben we de shortcut genomen dat we de absorberende en niet-uitkerende staten weglieten (namelijk de staat waarin de verzekerde overleden is). Voor het OP is het twee-staten model niet nodig om tot de correcte uitkomsten te komen, maar we doen dit als opmaat voor het PP.

Omdat we nu hoger-dimensionale gegevens nodig hebben (namelijk een lijst van matrices, ofwel een drie-dimensionale lijst), schakelen we over naar de Python package **NumPy** (https://numpy.org/). NumPy vormt de basis voor pandas, en is uitermate geschikt voor N-dimensionale data.

Allereerste importen we NumPy en een package uit de Python stdlib, namelijk itertools:

In [13]:
import itertools as it
import numpy as np

De overgangskansen Qs zijn:

In [14]:
Qs = np.array([[
    [0.9, 0.1], 
    [0.0, 1.0]
]] * 10)
Qs

array([[[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]],

       [[0.9, 0.1],
        [0. , 1. ]]])

De cumulatieve overgangskansen zijn:

In [15]:
Qcum = np.array(list(it.accumulate(Qs[:-1], np.matmul,  initial=np.identity(2))))
Qcum

array([[[1.        , 0.        ],
        [0.        , 1.        ]],

       [[0.9       , 0.1       ],
        [0.        , 1.        ]],

       [[0.81      , 0.19      ],
        [0.        , 1.        ]],

       [[0.729     , 0.271     ],
        [0.        , 1.        ]],

       [[0.6561    , 0.3439    ],
        [0.        , 1.        ]],

       [[0.59049   , 0.40951   ],
        [0.        , 1.        ]],

       [[0.531441  , 0.468559  ],
        [0.        , 1.        ]],

       [[0.4782969 , 0.5217031 ],
        [0.        , 1.        ]],

       [[0.43046721, 0.56953279],
        [0.        , 1.        ]],

       [[0.38742049, 0.61257951],
        [0.        , 1.        ]]])

De betalingsmatrices zijn:

In [16]:
Bs = np.array([[[0,0],[0,0]]] * 2 + [[[1, 0], [1, 0]]] * 8)
Bs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0]]])

De verdiscontering is:

In [17]:
W = 1 / (1 + df.cumulatieve_rente.to_numpy())
W

array([0.95238095, 0.90702948, 0.8638376 , 0.82270247, 0.78352617,
       0.7462154 , 0.71068133, 0.67683936, 0.64460892, 0.61391325])

We kunnen de kasstroom K in snel uitrekenen dankzij de NumPy functie [einsum()](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html). De functie implementeert de zogenaamde [Einstein summatie conventie](https://en.wikipedia.org/wiki/Einstein_notation), waarmee ingewikkelde matrix-vermenigvuldigingen in één klap uit te rekenen zijn.

De formule voor de actuarieele factor is:
$$
F(s) = \sum_{\tau=s}^{\infty} K(s, \tau) 
$$
waar de verdisconteerde kasstroom $K(s, \tau)$ gelijk is aan:
$$
K(s, \tau)   = \bar{Q}(s,\tau-1)[Q(\tau) \odot \tilde{B}(\tau))]  \iota  \iota W(s,\tau-s)
$$
Als we alle indices uitschrijven wordt de verdisconteerde kasstroom gelijk aan:
$$
K(s, \tau)_i = \sum_{j, k} \bar{Q}(s, \tau-1)_{ij} Q(\tau)_{jk} B(\tau)_{jk}  W(s,\tau-s)
$$
De $\tau$ tijds-afhankelijkheid zit in de NumPy lijsten die we hierboven hebben gedefinieerde in de eerste index. `W[0]` is bijvoorbeeld de verdiscontering in het eerste jaar, `W[1]` die in het tweede, etc. De $i$, $j$ en $k$ indices horen bij de staten van het rekenmodel. De verdisconteerde kasstroom kan dan als volgt uitgerekend worden:

In [18]:
K = np.einsum("tij,tjk,tjk,t->ti", Qcum, Qs, Bs, W)
K

array([[0.        , 0.        ],
       [0.        , 0.        ],
       [0.62973761, 0.        ],
       [0.53977509, 0.        ],
       [0.46266437, 0.        ],
       [0.39656946, 0.        ],
       [0.33991668, 0.        ],
       [0.29135715, 0.        ],
       [0.2497347 , 0.        ],
       [0.21405832, 0.        ]])

De factor is de som van de kasstroom:

In [19]:
factor = K.sum(axis=0)
factor

array([3.12381337, 0.        ])

## Bepaald Partnerpensioen

Het verschil tussen het OP hierboven en een PP is voornamelijk de betalingsmatrix: in het OP is de eerste staat (deelnemer in leven) uitkerend, en het PP is de twee staat (deelnemer OVL, partner in leven) uitkerend. We zetter hier gemakshalve de overlevingskansen van de partner, $p_y$, gelijk aan 1.

In [20]:
Bs = np.array([[[0,0],[0,0]]] * 2 + [[[0, 1], [0, 1]]] * 8)
Bs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]])

De kasstroom is dan:

In [21]:
K = np.einsum("tij,tjk,tjk,t->ti", Qcum, Qs, Bs, W)
K

array([[0.        , 0.        ],
       [0.        , 0.        ],
       [0.23409999, 0.8638376 ],
       [0.28292738, 0.82270247],
       [0.3208618 , 0.78352617],
       [0.34964594, 0.7462154 ],
       [0.37076465, 0.71068133],
       [0.38548221, 0.67683936],
       [0.39487421, 0.64460892],
       [0.39985494, 0.61391325]])

De daadwerkelijke kasstroom is die van de eerste staat, dus de eerste kolom. De tweede kolom is de kasstroom als de deelnemer vanaf het begin af aan al overleden zou zijn. De PP kasstroom wordt hoger naar verloop van tijd, in tegenstelling tot de OP kasstroom.

In [22]:
factor = K.sum(axis=0)
factor

array([2.73851113, 5.8623245 ])

De daadwerkelijke factor is ook hier het eerste getal. Het tweede getal is de factor voor wanneer de deelnemer vanaf het begin af aan al overleden zou zijn.